#!/usr/bin/python

DATETIME = None
ATMOSPHERIC_GRID = dict()
CLOUD_GRID = None
CLOUD_TEMP = 0.0
CLOUD_LAYERS = []
SOLAR_ZENITH_ANGLE = 0.0
S_A_INV_MATRIX = None
S_Y_INV_MATRIX = None
VARIANCE_RA = 0.0
RADIANCE_LBLDIS = None
RADIANCE_FTIR = []
RADIANCE_CLEARSKY = []
WAVENUMBER_FTIR = []
NOISE_FTIR = []
MCP = []
MCP_APRIORI = []
CHI2 = []
RESIDUUM = []
T_MATRIX = []
LBL_WORK = ''
MICROWINDOWS = None
FNAME = ''